# Check if running in interactive mode
if [[ -o interactive ]]; then
  # ZSH setup
  export ZSH="$HOME/.oh-my-zsh"
  export NVM_LAZY_LOAD=true
  export NVM_COMPLETION=true

  plugins=(zsh-syntax-highlighting zsh-completions zsh-autosuggestions fzf zsh-nvm)

  source $ZSH/oh-my-zsh.sh

  # Color correction for zsh-syntax-highlighting
  ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#626262'
  ZSH_HIGHLIGHT_STYLES[comment]='fg=#888888'
else
  # Non-interactive mode - minimal setup
  ZSH_DISABLE_COMPFIX=true
  # NVM
  [ -f /root/.nvm/nvm.sh ] && source /root/.nvm/nvm.sh
fi

# zsh history config
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
export HISTTIMEFORMAT="[%F %T] "
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_FIND_NO_DUPS

# TERM to prevent tmux not working with autosuggestion
export TERM=xterm-256color

# load starship
eval "$(starship init zsh)"

# load zoxide
eval "$(zoxide init zsh)"